SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cst323_clcproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fa8bcve3hdjavv78` DEFAULT CHARACTER SET utf8 ;
USE `fa8bcve3hdjavv78` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `EMAIL` VARCHAR(45) NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `DOB` VARCHAR(45) NULL DEFAULT NULL,
  `ROLE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `albums` ;

CREATE TABLE IF NOT EXISTS `albums` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ALBUM_TITLE` VARCHAR(45) NULL DEFAULT NULL,
  `POST_TIME` VARCHAR(45) NULL DEFAULT NULL,
  `DESCRIPTION` TEXT NULL DEFAULT NULL,
  `RATING` INT(11) NULL DEFAULT NULL,
  `ARTIST` VARCHAR(45) NULL DEFAULT NULL,
  `IMG_LINK` VARCHAR(45) NULL DEFAULT NULL,
  `USER_EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_USER_EMAIL`
    FOREIGN KEY (`USER_EMAIL`)
    REFERENCES `users` (`EMAIL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `users` (`EMAIL`, `USERNAME`, `PASSWORD`, `DOB`, `ROLE`) VALUES ("marc@gcu.edu", "marc", 1234, "", "Admin");
